# name: Build and Deploy Vue App

# on:
#   push:
#     branches:
#       - main  # or your deploy branch

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Node
#       uses: actions/setup-node@v3
#       with:
#         node-version: '22'  # adjust if needed

#     - name: Install dependencies
#       run: npm install

#     - name: Build Vue app
#       run: npm run build

#     - name: Copy files via SCP
#       uses: appleboy/scp-action@v0.1.4
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         source: "dist/*"
#         target: ${{ secrets.EC2_TARGET_DIR }}
